menu:
    Home: http://makmonty.com
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/makmonty
    Rss: /atom.xml

favicon: /favicon.png
logo: /makmonty-sombra-verde.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2018
